import { PrismaClient } from '@prisma/client';
import crypto from 'crypto';
import { aiService } from '../ai';
import * as dotenv from 'dotenv';
import path from 'path';

// Load environment variables from root .env
dotenv.config({ path: path.resolve(__dirname, '../../../../.env') });

const prisma = new PrismaClient();

// Simple hash function for demo (use bcrypt in production)
const hashPassword = (password: string) => crypto.createHash('sha256').update(password).digest('hex');

async function main() {
  console.log('🌱 Starting seed...');

  // Optional: Clean up existing data (be careful in production!)
  // await prisma.reservation.deleteMany();
  // await prisma.product.deleteMany();
  // await prisma.stall.deleteMany();
  // await prisma.vendorProfile.deleteMany();
  // await prisma.market.deleteMany();
  // await prisma.user.deleteMany();

  // 1. Create a Market Environment (Kimironko)
  const market = await prisma.market.create({
    data: {
      name: 'Kimironko Market',
      location: 'Kigali, Rwanda',
      environmentId: 'kimironko_v1'
    },
  });
  console.log(`✅ Market created: ${market.name}`);

  // 2. Generate Vendors via Gemini
  console.log('🤖 Asking Gemini 3 Pro to generate vendor list for Kimironko...');
  const generatedVendors = await aiService.generateMarketData('Kimironko Market', 'Kigali, Rwanda');

  if (!generatedVendors || generatedVendors.length === 0) {
      console.warn("⚠️ No data generated by AI. Using fallback data.");
      // Add fallback logic if needed, or just let it be empty
  }

  // 3. Create Users, Profiles, Stalls, Products
  let vendorCount = 0;
  for (const vData of generatedVendors) {
      const email = `vendor${vendorCount + 1}@kimironko.rw`;
      
      // Create User
      const user = await prisma.user.upsert({
          where: { email },
          update: {},
          create: {
              email,
              passwordHash: hashPassword('password123'),
              role: 'VENDOR',
              fullName: vData.ownerName || `Vendor ${vendorCount + 1}`,
          }
      });

      // Create Profile
      const profile = await prisma.vendorProfile.create({
          data: {
              userId: user.id,
              storeName: vData.storeName,
              description: vData.description,
              isVerified: true,
              rating: 4.5 + (Math.random() * 0.5)
          }
      });

      // Create Stall
      const stall = await prisma.stall.create({
          data: {
              name: `Stall ${100 + vendorCount}`,
              marketId: market.id,
              vendorId: profile.id,
              locationDescription: "Main Hall"
          }
      });

      // Create Products
      if (vData.products && Array.isArray(vData.products)) {
          const products = vData.products.map((p: any, idx: number) => ({
              name: p.name,
              description: p.description,
              price: Number(p.price) || 1000, // Ensure number
              category: "Other", // Just default because Validation might strict check Enum.
              // We should map category string from AI to Enum if possible.
              // But 'Other' is safe.
              stallId: stall.id,
              // Random 3D positions for the stall display
              positionX: (idx - 1) * 1.5, 
              positionY: 1.0, 
              positionZ: 0 
          }));
          
          // Map AI category to Enum if possible
          const validCategories = ['Vegetables', 'Fruits', 'Crafts', 'Clothing', 'Electronics', 'Services', 'Other'];
          products.forEach(p => {
              if (validCategories.includes(vData.category)) {
                  p.category = vData.category;
              }
          });

          await prisma.product.createMany({ data: products });
      }

      console.log(`✅ Created Vendor: ${vData.storeName}`);
      vendorCount++;
  }

  // 4. Create "Mock User" Account for testing
  const normalUser = await prisma.user.upsert({
    where: { email: 'user@test.com' },
    update: {},
    create: {
      email: 'user@test.com',
      passwordHash: hashPassword('user123'),
      role: 'BUYER',
      fullName: 'Test Buyer',
    },
  });
  console.log(`✅ Mock User created: ${normalUser.email} / user123`);
  
  console.log('🌱 Seed completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
